steps:
- name: 'gcr.io/cloud-builders/mvn'
  args: ['clean', 'install','app', 'deploy']
  timeout: 1200s
options:
  machineType: 'E2_HIGHCPU_8'
  logging: 'CLOUD_LOGGING_ONLY'
  # You can add the following line to specify a logs bucket:
  # logsBucket: 'my-logs-bucket'
